name: rancher-provisioner
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go build -v .

    - uses: engineerd/setup-kind@v0.1.0

    - name: Testing
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        kubectl get nodes
        echo ">>> delete KIND's default storageclass"
        kubectl delete storageclass standard || true
        echo ">>> deploy hostpath provisioner"
        kubectl apply -f ${GITHUB_WORKSPACE}/hack/github/rancher-provisioner.yaml
        echo ">>> run pod"
        kubectl apply -f ${GITHUB_WORKSPACE}/hack/github/rancher-provisioner-pod.yaml
        sleep 5
        echo ">>> describe pod"
        kubectl describe pod -n default volume-test
        sleep 10
        echo ">>> show pod logs"
        kubectl logs -n default volume-test
        sleep 30
        echo ">>> describe pod"
        kubectl get pods -n default
        kubectl describe pod -n default volume-test
        kubectl get pvc
        kubectl get pv
